name: ravepay
description: RavePay by Flutterwave Dart SDK. http://rave.flutterwave.com
version: 0.0.1
author: Jeremiah Ogbomo <jeremiahogbomo@gmail.com>
homepage: https://github.com/jogboms/ravepay.dart

environment:
  sdk: ">=2.6.0-dev <3.0.0"

dependencies:
  crypto: ^2.1.4
  tripledes: ^2.1.0
  http: ^0.12.0+2
  built_value: ^6.8.2
  built_collection: ^4.2.2
  meta: ^1.1.7
  convert: ^2.1.1

dev_dependencies:
  test: ^1.9.0
  pedantic: ^1.8.0
  test_coverage:
    git:
      url: https://github.com/jogboms/test-coverage.git
  build_runner: ^1.7.2
  built_value_generator: ^6.8.2